### ISSUE TITLE
Extending or modifying existing nodes

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_workflow#7]
From @JNmpi in pyiron/pyiron_contrib#855. @samwaseda you probably want to read this one too.

> #### Allow substitution of nodes in workflows
> ```python
> from pyiron_contrib.workflow.function import single_value_node
> 
> @single_value_node(
>     output_labels=['new structure node called']
> )
> def new_structure_node(structure):
>     print ('structure')  # show that the new node has been successfully included
>     return structure
> ```
> 
>  ```python
> wf = Workflow('simple_lammps_calculation')
> 
> structure = wf.create.atomistics.Bulk(cubic=True, name="Al", label='structure')
> 
> lammps_job = wf.create.lammps.LammpsStaticNode(label='lammps_job')
> lammps_job.structure = new_structure_node  # does not work
> # lammps_job.structure.replace_with(new_structure_node)  # more explicit syntax, not sure whether needed if above construct works
> 
> 
> lammps_job.inputs.structure = structure
> 
> wf.run()
> ```
> 
>  ```
> potential starts
> potential name:  None
> start shell
> end shell
> parse dump file
> parse log file
> 
> 
> 
> 
> 
> {'lammps_job__engine__output': <pyiron_contrib.workflow.node_library.lammps.ShellOutput at 0x290111050>,
>  'lammps_job__collect_output__generic': <pyiron_contrib.workflow.node_library.lammps.GenericOutput at 0x1074adf50>}
> ```
> 
> **Issue:** Being able to replace a node in a workflow or macro node would be a powerful extension. It would allow to test and explore new functionality without having to modify the actual code. This would dramatically simplify the way users and developers could implement new ideas and would dramatically lower the barrier to do so (no git, branches etc. needed).

So I actually see two issues here, the first is how to modify and extend existing function nodes, and the second is how to replace a node in a workflow or macro. Replacing nodes in workflow/macro instances is already possible, but can be made much easier; re-using function node functionality is not really possible right now but easily could be.

# On replacing a node in a composite

```python
> lammps_job.structure = new_structure_node  # does not work
> # lammps_job.structure.replace_with(new_structure_node)  # more explicit syntax, not sure whether needed if above construct works
```

In this example, the first line won't work on a couple of levels: first, we don't have the infrastructure for assigning a new node _class_ to an existing owned node _instance_. `Composite.__setattr__` and `__getattr__` look like this:

```python
    def __setattr__(self, key: str, node: Node):
        if isinstance(node, Node) and key != "parent":
            self.add(node, label=key)
        else:
            super().__setattr__(key, node)

    def __getattr__(self, key):
        try:
            return self.nodes[key]
        except KeyError:
            # Raise an attribute error from getattr to make sure hasattr works well!
            raise AttributeError(
                f"Could not find attribute {key} on {self.label} "
                f"({self.__class__.__name__}) or in its nodes ({self.nodes.keys()})"
            )
```

So what's happening is that `lammps_job.structure = new_structure_node` is going to the super call and behaving like a perfectly normal attribute assignment to a python class instance. But we never see this new value of `lammps_job.structure` because the attribute retrieval continues to find the old node and return that instead.

As you suggest in the second line, maybe we could write some infrastructure so that assigning a node class to an existing node attempts a replacement. This infrastructure would need to keep track of the existing connections and IO values, destroy the old node, instantiate the new node, and populate its values and connections with those held by the old node. 

This brings us to the second problem: the new node needs identical IO. In this particular case we might get away safe, because even though the output is renamed from `structure` to `new structure node called`.

With all that said, we _can_ replace nodes in workflows and macros by removing the old node and assigning a new node instance, provided that the new node's IO is a superset of the old node's IO. The following (probably) accomplishes this:

```python
from pyiron_contrib.workflow import Workflow

from pyiron_contrib.workflow.node_library.lammps import nodes as lammps_nodes

Workflow.create.register("lammps", *lammps_nodes)

structure = Workflow.create.atomistics.Bulk(cubic=True, name="Cu", label='structure')

@Workflow.wrap_as.single_value_node('new structure node called')
def new_structure_node(structure):
    print ('structure')  # show that the new node has been successfully included
    return structure

wf = Workflow('simple_lammps_calculation')

structure = wf.create.atomistics.Bulk(cubic=True, name="Al", label='structure')

lammps_job = wf.create.lammps.LammpsStaticNode(label='lammps_job')
lammps_job.inputs.structure = structure
lammps_job.inputs.potential = '1995--Angelo-J-E--Ni-Al-H--LAMMPS--ipr1'

@Workflow.wrap_as.single_value_node('structure')
def new_structure_node(structure):
    print ('new structure node called')  # show that the new node has been successfully included
    return structure

from pyiron_contrib.workflow.channels import InputData, OutputData, InputSignal, OutputSignal

def replace_node(existing, new):
    connections = existing.disconnect()
    for (c1, c2) in connections:
        if c1.node is existing:
            copy_connection(c1, new, c2)
        else:
            copy_connection(c2, new, c1)
    label = existing.label
    composite = existing.parent
    composite.remove(existing)
    setattr(composite, label, new)
        
def copy_connection(existing_channel, new_node, target_channel):
    print(f"Copying {existing_channel.label}'s connection to {target_channel.label} to the node {new_node.label}")
    if isinstance(existing_channel, InputData):
        new_source = new_node.inputs
    elif isinstance(existing_channel, OutputData):
        new_source = new_node.outputs
    elif isinstance(existing_channel, InputSignal):
        new_source = new_node.signals.input
    elif isinstance(existing_channel, OutputSignal):
        new_source = new_node.signals.output
    else:
        raise TypeError(f"Expected a known channel type but got {existing_channel}")
    new_source[existing_channel.label].connect(target_channel)


replace_node(lammps_job.structure, new_structure_node())
```

I say "probably" both with and without the node replacement I get an assertion error that the working directory is missing. But I can look at `wf.draw()` and both the data and node connections are getting replaced just fine.

TODO:
- [x] ~Define `Composite.replace_node` similar to above but with some safety rails~ #26 
- [x] ~Add syntactic sugar in `Composite.__setattr__` so that when it receives `type[Node]` to an existing node label, it attempts to instantiate the new type and call replace using the existing and newly instantiated nodes~ #26 
- ~Maybe? Set `remove` and `replace` directly on `Node` where it tries to remove/replace itself on its parent, and then just override these methods on `Composite` (or use `remove/replace_child`?) so they can work on owned nodes instead, if the provided arguments suggest that's what's desired.~ Not for now.

# On modifying function nodes

This topic got me thinking that there really is no nice way to inherit from our function-nodes-defined-by-wrapper. A big part of this problem is that the `node_function` is only actually assigned at _instantiation_, so we can't do something like this:

```python
from pyiron_contrib.workflow import Workflow

@Workflow.wrap_as.single_value_node()
def labeled_scatter(x, y, label=None):
    plot = Workflow.create.standard.Scatter.node_function(x, y)
    plot.label = label
    if label is not None:
        plot.legend()
    return plot
```

The `node_function` is always a static method, so there really is no barrier to having it available already at the class level, thus making this sort of function-inheritance possible (well, function re-use really). It's possible we could come up with even more syntactic sugar so it's easier to copy signature and type hinting and stuff, but honestly I'd already be content with being able to access the function at all.

TODO:
- [x] ~Make `node_function` optional input, but raise an error if it's not provided _and_ the class doesn't have the attribute at instantiation~ #27 
- [x] ~Modify the decorators so that the add a `node_function` method to the dynamically defined class and remove the `node_function` input instead of overriding the `node_function` input argument to be a particular value.~ #27

**Comment by liamhuber** [comment]
#26 You can pop a node right out of a macro or workflow and insert another one in its place -- the replacement takes over all connections etc. There's a few ways to do this syntactically, but you need either a replacement class or replacement instance, and that replacement needs to have compatible IO with the node its replacing (obviously, since it needs to take over its connections!)

#27 Now you can access function node behaviour right at the class level. This lets you make modified versions of function nodes, or even patch together a sort of functionalized-macro right from the raw node functions if you have a node library.

Docstrings and demo notebook are updated, and the PRs themselves have little demos, but the basics are easy enough to see in snapshots of the updated notebook:

<img width="696" alt="Screen Shot 2023-10-13 at 12 21 23" src="https://github.com/pyiron/pyiron_workflow/assets/20283329/bf61ecc9-a51a-4e0b-ae45-b42fc0ec5aa1">

<img width="958" alt="Screen Shot 2023-10-13 at 12 22 01" src="https://github.com/pyiron/pyiron_workflow/assets/20283329/ca6f1076-009f-4e7e-a82e-eff1ef3bf71a">
